1. Define a string with a value equal to “Python is fun!”. Print every third character of this string.

In [6]:
string = "Python is fun!"
char = string[0:len(string):3]
print (char)

Ph  n


2. Create three list variables named 'StudentName', 'ID', and 'EmailAddress'. Add 5 random values in these lists and print them.

In [7]:
{"StudentName":"George, Ava, Julia, Stephen, Carla", "ID":( 252 , 253, 254, 255, 256) , "EmailAddress": "georg252@deakin.edu.au, ava253@deakin.edu.au, julia254@deakin.edu.au, step255@deakin.edu.au, carl256@deakin.edu.au"}

{'StudentName': 'George, Ava, Julia, Stephen, Carla',
 'ID': (252, 253, 254, 255, 256),
 'EmailAddress': 'georg252@deakin.edu.au, ava253@deakin.edu.au, julia254@deakin.edu.au, step255@deakin.edu.au, carl256@deakin.edu.au'}

3. Create a dictionary variable with three keys, which are named same as the list created in the previous problem. Insert the previously created lists in the dictionary variable and print it.

In [24]:
test_dict = {}  
# Initialize keys
test_keys = ['Studentname', 'ID', 'EmailAddress']
lst = [('George', 'Ava', 'Julia', 'Stephen','Carla'),(252,253,254,255,256), ('georg252@deakin.edu.au','ava253@deakin.edu.au','julia254@deakin.edu.au','step255@deakin.edu.au','carl256@deakin.edu.au')]
test_dict = dict(zip(test_keys, lst)) 
print(test_dict)

{'Studentname': ('George', 'Ava', 'Julia', 'Stephen', 'Carla'), 'ID': (252, 253, 254, 255, 256), 'EmailAddress': ('georg252@deakin.edu.au', 'ava253@deakin.edu.au', 'julia254@deakin.edu.au', 'step255@deakin.edu.au', 'carl256@deakin.edu.au')}


4.  Define a numeric variable 'energy' and assign value either 1 or 2. Print "Apple" if the value of energy variable is 1 otherwise print "Banana". What will your program print if energy=10? 

In [36]:
energy= input ('value')
if energy==1:
  print('Apple')
else:
  print ('Banana')

value10
Banana


5.  Print numbers between 0 and 2000 separated by line, which are divisible by 5.

In [40]:
for i in range(0, 2000):
    if i % 5 == 0:
        print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
295
300
305
310
315
320
325
330
335
340
345
350
355
360
365
370
375
380
385
390
395
400
405
410
415
420
425
430
435
440
445
450
455
460
465
470
475
480
485
490
495
500
505
510
515
520
525
530
535
540
545
550
555
560
565
570
575
580
585
590
595
600
605
610
615
620
625
630
635
640
645
650
655
660
665
670
675
680
685
690
695
700
705
710
715
720
725
730
735
740
745
750
755
760
765
770
775
780
785
790
795
800
805
810
815
820
825
830
835
840
845
850
855
860
865
870
875
880
885
890
895
900
905
910
915
920
925
930
935
940
945
950
955
960
965
970
975
980
985
990
995
1000
1005
1010
1015
1020
1025
1030
1035
1040
1045
1050
1055
1060
1065
1070
1075
1080
1085
1090
1095
1100
1105
1110
1115
1120
1125
1130
1135
1140
1145
1150
1155
1160
1165
1170
1175
1180
1185
1190
1195
1200
1205
1210
1215
12

6. Is it possible to break a loop before executing for the defined number of iterations? If yes, provide an example using While loop structure. Otherwise, explain your answer (why and how).  
Yes, it is possible to break a loop before executing for the defined number of iterations. It breaks the execution of the loop. 

7. Create a function with two input parameters say (x, y) and return output values by doing operations such as 'x+y' and 'x-y'. Call the function with (4,7) and print the outputs.

In [50]:
def add(x, y):
    sum = x + y
    print ("Sum: ", sum)
add(4,7)  

Sum:  11


In [51]:
def minus(x, y):
    sep = x - y
    print ("Sep: ", sep)
minus(4,7)


Sep:  -3


8. Create and display a 3X3 Identity matrix and multiply it with a 3x4 Random matrix.

In [64]:
import numpy as np
dimension = 3
identity = np.identity(dimension, dtype="int")
print(identity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [56]:
import numpy as np
matrix = np.arange(10,22).reshape((3, 4))
print(matrix)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [66]:
dumpy = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
 
for i in range(len(identity)):
    for j in range(len(matrix[0])):
        for k in range(len(matrix)):
            dumpy[i][j] += identity[i][k] * matrix[k][j]
for l in dumpy:
    print(l)

[10, 11, 12, 13]
[14, 15, 16, 17]
[18, 19, 20, 21]


8. Create a 5x2 matrix, initialise with random values and print it. Now, transpose the matrix and print it. How the transposed matrix is different from original matrix? 

The transpose matrix changes from row to column of original matrix. The 5*2 dimension is changed to 2*5 dimension. Therefore, it chnages the dimension of the original matrix. 

In [73]:
import numpy as np
ran_matrix = np.arange(0,10).reshape((5, 2))
print(ran_matrix)
transpose_matrix = np.transpose(ran_matrix)
print (transpose_matrix)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


 10. Read the data stored in the "data.csv" file as a matrix. The row of the matrix represents data point or instance and the column represents the variable or feature. Print the number of data instances and variables present in this dataset. Calculate mean of the second variable and deduct this mean from original values of the variable. Print both original and modified values of the variable.

In [75]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
import io
data = pd.read_csv(io.BytesIO(uploaded['data.csv']))

Saving data.csv to data.csv


In [79]:
array = np.loadtxt(open("data.csv", "rb"), delimiter=",")
print (array)

[[3.3816 3.3891]
 [4.5279 5.8542]
 [2.6557 4.412 ]
 [2.7652 3.7154]
 [2.8466 4.1755]
 [3.8907 6.4884]
 [3.4758 3.6328]
 [5.9113 6.6808]
 [3.9289 5.0984]
 [4.5618 5.6233]
 [4.5741 5.3977]
 [4.3717 5.4612]
 [4.1917 4.9547]
 [5.2441 4.6615]
 [2.8358 3.768 ]
 [5.6353 6.3121]
 [4.6863 5.6652]
 [2.8505 4.6265]
 [5.1102 7.3632]
 [5.1826 4.6465]
 [5.7073 6.681 ]
 [3.5797 4.8028]
 [5.6394 6.1204]
 [4.2635 4.6894]
 [2.5365 3.8845]
 [3.2238 4.9426]
 [4.9295 5.955 ]
 [5.793  5.1084]
 [2.8168 4.819 ]
 [3.8888 5.1004]
 [3.3432 5.893 ]
 [5.8797 5.5214]
 [3.1039 3.8571]
 [5.3315 4.6807]
 [3.3754 4.5654]
 [4.7767 6.2544]
 [2.6757 3.731 ]
 [5.5003 5.6795]
 [1.7971 3.2475]
 [4.3225 5.1111]
 [4.421  6.0256]
 [3.1793 4.4369]
 [3.0335 3.9788]
 [4.6093 5.8798]
 [2.9638 3.3002]
 [3.9718 5.4077]
 [1.1802 2.8787]
 [1.919  5.0711]
 [3.9552 4.5053]
 [5.118  6.0851]]


In [82]:
#Print number of data instances and variables present in the dataset
data_instances = len(data.index)
print (data_instances)
variables = len (data.columns)
print (variables)

49
2
